apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: test
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: gha-demo-app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"

---
kind: Service
apiVersion: v1
metadata:
  name: demo
  namespace: test
spec:
  selector:
    app: demo
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: demo
  namespace: test
spec:
  rules:
  - host: demo.bukolajohnson.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 8080